insert into 
    public.provinces(id,province)
values
    ('1','Abra'),
    ('2','Agusan del Norte'),
    ('3','Agusan del Sur'),
    ('4','Aklan'),
    ('5','Albay'),
    ('6','Antique'),
    ('7','Apayao'),
    ('8','Aurora'),
    ('9','BARMM'),
    ('10','Basilan'),
    ('11','Bataan'),
    ('12','Batanes'),
    ('13','Batangas'),
    ('14','Benguet'),
    ('15','Biliran'),
    ('16','Bohol'),
    ('17','Bukidnon'),
    ('18','Bulacan'),
    ('19','Cagayan'),
    ('20','Camarines Norte'),
    ('21','Camarines Sur'),
    ('22','Camiguin'),
    ('23','Capiz'),
    ('24','Catanduanes'),
    ('25','Cavite'),
    ('26','Cebu'),
    ('27','Cotabato'),
    ('28','Davao Occidental'),
    ('29','Davao Oriental'),
    ('30','Davao de Oro'),
    ('31','Davao del Norte'),
    ('32','Davao del Sur'),
    ('33','Dinagat Islands'),
    ('34','Eastern Samar'),
    ('35','Guimaras'),
    ('36','HUC'),
    ('37','Ifugao'),
    ('38','Ilocos Norte'),
    ('39','Ilocos Sur'),
    ('40','Iloilo'),
    ('41','Isabela'),
    ('42','Kalinga'),
    ('43','La Union'),
    ('44','Laguna'),
    ('45','Lanao del Norte'),
    ('46','Lanao del Sur'),
    ('47','Leyte'),
    ('48','Maguindanao del Norte'),
    ('49','Maguindanao del Sur'),
    ('50','Marinduque'),
    ('51','Masbate'),
    ('52','Misamis Occidental'),
    ('53','Misamis Oriental'),
    ('54','Mountain Province'),
    ('55','Negros Occidental'),
    ('56','Negros Oriental'),
    ('57','Northern Samar'),
    ('58','Nueva Ecija'),
    ('59','Nueva Vizcaya'),
    ('60','Occidental Mindoro'),
    ('61','Oriental Mindoro'),
    ('62','Palawan'),
    ('63','Pampanga'),
    ('64','Pangasinan'),
    ('65','Quezon'),
    ('66','Quirino'),
    ('67','Rizal'),
    ('68','Romblon'),
    ('69','Samar'),
    ('70','Sarangani'),
    ('71','Siquijor'),
    ('72','Sorsogon'),
    ('73','South Cotabato'),
    ('74','Southern Leyte'),
    ('75','Sultan Kudarat'),
    ('76','Sulu'),
    ('77','Surigao del Norte'),
    ('78','Surigao del Sur'),
    ('79','Tarlac'),
    ('80','Tawi-Tawi'),
    ('81','Zambales'),
    ('82','Zamboanga Sibugay'),
    ('83','Zamboanga del Norte'),
    ('84','Zamboanga del Sur');
