create table "public"."monthly_report" (
    "id" bigint generated by default as identity not null,
    "created_at" date not null,
    "driver_id" uuid not null,
    "counter" bigint not null
);


alter table "public"."monthly_report" enable row level security;

CREATE UNIQUE INDEX payment_pkey ON public.monthly_report USING btree (id);

alter table "public"."monthly_report" add constraint "payment_pkey" PRIMARY KEY using index "payment_pkey";

alter table "public"."monthly_report" add constraint "payment_driver_id_fkey" FOREIGN KEY (driver_id) REFERENCES auth.users(id) ON UPDATE CASCADE not valid;

alter table "public"."monthly_report" validate constraint "payment_driver_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.monthly_agg()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
begin
INSERT INTO public.monthly_report(created_at, driver_id, counter)
  SELECT current_date::date, driver::uuid, counter::bigint FROM public.pasada
  WHERE counter>0;
update public.pasada
  set counter=0
  where counter>0;
return true;
end $function$
;
revoke all on table public.monthly_report from public,anon,authenticated;
revoke execute on function public.monthly_agg from public,anon,authenticated;
grant all on table public.monthly_report to postgres;
grant execute on function public.monthly_agg to postgres;
grant delete on table "public"."monthly_report" to "service_role";

grant insert on table "public"."monthly_report" to "service_role";

grant references on table "public"."monthly_report" to "service_role";

grant select on table "public"."monthly_report" to "service_role";

grant trigger on table "public"."monthly_report" to "service_role";

grant truncate on table "public"."monthly_report" to "service_role";

grant update on table "public"."monthly_report" to "service_role";


